### ISSUE TITLE
Error: Unable to determine file size

### ISSUE THREAD

**Issue by Lewiscowles1986** [evanlucas/remote-file-size#3]
Using https://github.com/adamisntdead/poke an error is thrown that seems to be from this library

```
Error: Unable to determine file size
    at Request._callback (/home/lewis/.nvm/versions/node/v8.9.4/lib/node_modules/poke-site/node_modules/remote-file-size/index.js:26:17)
    at Request.self.callback (/home/lewis/.nvm/versions/node/v8.9.4/lib/node_modules/poke-site/node_modules/request/request.js:188:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/lewis/.nvm/versions/node/v8.9.4/lib/node_modules/poke-site/node_modules/request/request.js:1171:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/lewis/.nvm/versions/node/v8.9.4/lib/node_modules/poke-site/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Example URL: https://www.stormykromer.com/giftcertificates.php

No idea why but it's across BigCommerce software, so maybe no `content-length` header in response?

Are you aware of any way to handle other than throwing an error?

**Comment by Lewiscowles1986** [comment]
Relates to https://github.com/adamisntdead/poke/issues/1

**Comment by evanlucas** [comment]
I'm not sure from where that error is being thrown. This package calls the callback with the error as the first argument (https://github.com/evanlucas/remote-file-size/blob/master/index.js#L26). It does look like the error should be handled better [here](https://github.com/adamisntdead/poke/blob/master/lib/image-size.js#L33-L37) though

**Comment by Lewiscowles1986** [comment]
The error is being thrown once this library realizes it cannot read content-length (as it's main-case is to issue a HEAD and not GET there is no body). There should be a way to not throw that error though, it's a false positive.

**Comment by evanlucas** [comment]
The error isn't actually thrown from this package though. It is being thrown somewhere else. Line 26 of the package's index.js calls the callback with an error, so the consumer of this package will need to handle that.

**Comment by Lewiscowles1986** [comment]
Re-read, top line is the source, the message even matches this lib. the rest is just going over the last things called.

`/home/lewis/.nvm/versions/node/v8.9.4/lib/node_modules/poke-site/*node_modules/remote-file-size/index.js:26*`

**Comment by evanlucas** [comment]
If the error was thrown, there would be a caret showing where it was thrown in the stack trace. https://github.com/adamisntdead/poke/blob/master/lib/image-size.js#L34 is why the error is being printed.
